/**
 * Golden-vector tests for the draft-16 MOQ wire codec.
 *
 * The expected hex strings come straight from Eyevinn's own wire encoder (our
 * server) — see spatial-mixer/plan/moq-draft14/golden/draft16-vectors.json,
 * generated by internal/wire/golden_panaudia_test.go. If the server's encoder
 * changes, regenerate that file and update these constants.
 */

import { describe, it, expect } from 'vitest';
import {
  buildClientSetup,
  buildSubscribe,
  buildAnnounce,
  buildObjectDatagram,
  parseSubscribeOk,
  encodeParams,
  decodeParams,
  MessageBuilder,
  MOQ_TRANSPORT_VERSION,
  type Kvp,
} from '../../src/moq/moq-transport.js';
import { MoqRole, MoqFilterType } from '../../src/moq/types.js';

const toHex = (b: Uint8Array): string =>
  Array.from(b).map((x) => x.toString(16).padStart(2, '0')).join('');
const fromHex = (h: string): Uint8Array =>
  new Uint8Array((h.match(/../g) ?? []).map((x) => parseInt(x, 16)));

// Golden vectors (Eyevinn draft-16).
const GOLDEN = {
  client_setup: '20000401024064',
  subscribe_audio_out_auth_resume:
    '0300480204036f757405617564696f0b6f7075732d73746572656f066e6f64652d310006030e746573742d6a77742d746f6b656e0d0110408001010201018000fedf0800000123456789ab',
  subscribe_audio_out_plain:
    '03002b0404036f757405617564696f0b6f7075732d73746572656f066e6f64652d31000410011040800101020101',
  subscribe_ok: '04000902040209020a051901',
  announce_audio_in: '06001d060402696e05617564696f096f7075732d6d6f6e6f066e6f64652d3100',
  object_datagram_audio: '0004c000018bcfe5687b0000fcfffe0102',
};

const NS_AUDIO_OUT = ['out', 'audio', 'opus-stereo', 'node-1'];
const NS_AUDIO_IN = ['in', 'audio', 'opus-mono', 'node-1'];

describe('draft-16 wire codec — golden vectors', () => {
  it('version constant is 0xff000010', () => {
    expect(MOQ_TRANSPORT_VERSION).toBe(0xff000010);
  });

  it('CLIENT_SETUP (no version list, no ROLE, MAX_REQUEST_ID=100)', () => {
    const msg = buildClientSetup([MOQ_TRANSPORT_VERSION], MoqRole.PUBSUB, undefined, 100);
    expect(toHex(msg)).toBe(GOLDEN.client_setup);
  });

  it('SUBSCRIBE with auth + ResumeHLC (delta-encoded params, sorted)', () => {
    const msg = buildSubscribe({
      subscribeId: 2,
      namespace: NS_AUDIO_OUT,
      trackName: '',
      filterType: MoqFilterType.LATEST_OBJECT,
      authorization: 'test-jwt-token',
      resumeOpId: 0x00000123456789abn,
    });
    expect(toHex(msg)).toBe(GOLDEN.subscribe_audio_out_auth_resume);
  });

  it('SUBSCRIBE plain (only the moved params)', () => {
    const msg = buildSubscribe({
      subscribeId: 4,
      namespace: NS_AUDIO_OUT,
      trackName: '',
      filterType: MoqFilterType.LATEST_OBJECT,
    });
    expect(toHex(msg)).toBe(GOLDEN.subscribe_audio_out_plain);
  });

  it('ANNOUNCE (no params)', () => {
    const msg = buildAnnounce({ requestId: 6, namespace: NS_AUDIO_IN });
    expect(toHex(msg)).toBe(GOLDEN.announce_audio_in);
  });

  it('OBJECT_DATAGRAM (audio, wire-identical to draft-11)', () => {
    const msg = buildObjectDatagram(4, 1700000000123n, 0n, 0, fromHex('fcfffe0102'));
    expect(toHex(msg)).toBe(GOLDEN.object_datagram_audio);
  });

  it('parses SUBSCRIBE_OK (TrackAlias + largest from params)', () => {
    // Strip the [type][len16] frame, then parse the content.
    const full = fromHex(GOLDEN.subscribe_ok);
    const content = full.subarray(3); // type(1) + length(2)
    const ok = parseSubscribeOk(content, 0);
    expect(ok.subscribeId).toBe(2);
    expect(ok.trackAlias).toBe(4);
    expect(ok.contentExists).toBe(true);
    expect(ok.largestGroupId).toBe(10n);
    expect(ok.largestObjectId).toBe(5n);
    expect(ok.groupOrder).toBe(1);
  });
});

describe('KVP delta encoding', () => {
  it('round-trips a mixed param list (even varint + odd bytes, sorted)', () => {
    const params: Kvp[] = [
      { type: 0xff01, value: new Uint8Array([1, 2, 3, 4, 5, 6, 7, 8]) }, // odd, out of order
      { type: 0x10, value: 1n }, // even
      { type: 0x03, value: new Uint8Array([9, 9]) }, // odd
      { type: 0x20, value: 128n }, // even
    ];
    const b = new MessageBuilder();
    encodeParams(b, params);
    const { params: out } = decodeParams(b.build(), 0);

    expect(out.get(0x10)).toBe(1n);
    expect(out.get(0x20)).toBe(128n);
    expect(out.get(0x03)).toEqual(new Uint8Array([9, 9]));
    expect(out.get(0xff01)).toEqual(new Uint8Array([1, 2, 3, 4, 5, 6, 7, 8]));
  });
});
